within ComputerCooling.Icons;

model DuctIcon

annotation(
    Diagram,
    Icon(graphics = {Bitmap(extent = {{-100, -100}, {100, 100}}, imageSource = "iVBORw0KGgoAAAANSUhEUgAAASAAAABACAYAAAC6AKpuAAAACXBIWXMAAAsSAAALEgHS3X78AAABB0lEQVR4nO3cMQoCUQxAwUS8/5UjtlaCxUOYucDCfnikCNmZuQEIPPx0oCJAQEaAgIwAARkBAjICBGQECMgIEJARICCzdxahgYYJCMgIEJARICAjQEBGgICMAAEZAQIyz88P7+5Xi0F3t54NmB+6YQICMgIEZAQIyAgQkBEgICNAQEaAgIwAARkHyYCMCQjICBCQESAgI0BARoCAjAABGQECMgIEZAQIyDjJCvzMSVbg7wgQkBEgICNAQEaAgIwAARkBAjICBGScZAUyJiAgI0BARoCAjAABGQECMgIEZAQIyLyPA1kEAhImICAjQEBGgICMAAEZAQIyAgRkBAjICBCQESCgMTMvGeEbdWnsCgcAAAAASUVORK5CYII=")}));
end DuctIcon;
