/* Additional record code for T05_3DICE_Integration_T05_Interface3DICE generated by the OpenModelica Compiler OpenModelica 1.18.1. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "T05_3DICE_Integration_T05_Interface3DICE_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

